### ISSUE TITLE
Rclone beta: 'panic: runtime error: invalid memory address or nil pointer dereference'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [mmozeiko/RcloneBrowser#152]
I was running this software:

rclone v1.48.0-147-g873e87fc-beta
- os/arch: linux/amd64
- go version: go1.12.7
rclone-browser 1.2

All my attempts at restoring files, via rclone-browser, yielded the following.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x99aa59]

goroutine 1 [running]:
github.com/rclone/rclone/fs/operations.moveOrCopyFile(0x183af40, 0xc0000ba010, 0x184f760, 0xc000161c00, 0x0, 0x0, 0x7fffc9f564bf, 0x9, 0x7fffc9f564bf, 0x9, ...)
/home/travis/gopath/src/github.com/rclone/rclone/fs/operations/operations.go:1640 +0xe9
github.com/rclone/rclone/fs/operations.CopyFile(...)
/home/travis/gopath/src/github.com/rclone/rclone/fs/operations/operations.go:1743
github.com/rclone/rclone/cmd/copy.glob..func1.1(0xc00000c400, 0xc000000180)
/home/travis/gopath/src/github.com/rclone/rclone/cmd/copy/copy.go:81 +0xf3
github.com/rclone/rclone/cmd.Run(0xc000340101, 0x23f5620, 0xc0005dfd38)
/home/travis/gopath/src/github.com/rclone/rclone/cmd/cmd.go:234 +0xc7
github.com/rclone/rclone/cmd/copy.glob..func1(0x23f5620, 0xc00034a000, 0x2, 0x12)
/home/travis/gopath/src/github.com/rclone/rclone/cmd/copy/copy.go:77 +0x129
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x23f5620, 0xc0000ede60, 0x12, 0x12, 0x23f5620, 0xc0000ede60)
/home/travis/gopath/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x23f2420, 0x5d57371e, 0x2408fa0, 0xc0000ae058)
/home/travis/gopath/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(...)
/home/travis/gopath/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:864
github.com/rclone/rclone/cmd.Main()
/home/travis/gopath/src/github.com/rclone/rclone/cmd/cmd.go:499 +0x96
main.main()
/home/travis/gopath/src/github.com/rclone/rclone/rclone.go:13 +0x20
```

The files remain accessible via rclone itself. I found that V1.48 or rclone was out of beta. I installed the non-beta version of 1.48. Now rclone-browser works again. Here is the software I have *now*.

rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6
rclone-browser 1.2

OS: Linux Mint 19.2 Cinnamon

**Comment by mmozeiko** [comment]
This is crash in rclone itself, report it to [rclone issues](https://github.com/rclone/rclone/issues).
